booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('booking/', views.IndexView.as_view(), name='index'),
    path('booking/<int:pk>', views.SingleView.as_view(), name='single'),
    path('booking/add/', views.AddView.as_view(), name="add"),
    path('booking/posts/', views.PostsView.as_view(), name="posts"),
    path('booking/edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('booking/verify/<int:pk>/', views.VerifyView.as_view(), name='verify'),
    path('booking/cancel/<int:pk>/', views.CancelView.as_view(), name='cancel'),
    path('booking/delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('coworkingSpace.urls', namespace='coworkingSpace')),
    path('', include('booking.urls', namespace='booking')),
    path('accounts/', include('accounts.urls'))
]

main/urls.py
from django.urls import path

from main.views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
]

booking/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from coworkingSpace.models import CoworkingSpace


class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    coworking_space = models.ForeignKey(CoworkingSpace, on_delete=models.CASCADE)
    ticket_amount = models.IntegerField(default=0)
    payment_status = models.BooleanField(default=False)
    booking_status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('booking:single', args = [self.id])

    def __str__(self):
        return self.id

booking/forms.py
from django import forms
from .models import Booking

class BookingForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['user', 'coworking_space', 'ticket_amount']

class VerifyForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['payment_status']

class CancelForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['booking_status']

booking/views.py
from .models import Booking
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView, TemplateView
from django.urls import reverse_lazy

# Create your views here.

class IndexView(ListView):
    model = Booking
    template_name = 'booking/index.html'
    context_object_name = 'index'

class SingleView(DetailView):
    model = Booking
    template_name = 'booking/single.html'
    context_object_name = 'post'

class PostsView(ListView):
    model = Booking
    template_name = 'booking/posts.html'
    context_object_name = 'posts_list'

class AddView(CreateView):
    model = Booking
    template_name = 'booking/add.html'
    fields = ['user', 'coworking_space', 'ticket_amount']
    success_url = reverse_lazy('booking:posts')

class EditView(UpdateView):
    model = Booking
    template_name = 'booking/update.html'
    fields = ['user', 'coworking_space', 'ticket_amount']
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('booking:posts')

class VerifyView(UpdateView):
    model = Booking
    template_name = 'booking/update_verify.html'
    fields = ['payment_status']
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('booking:posts')

class CancelView(UpdateView):
    model = Booking
    template_name = 'booking/update_cancel.html'
    fields = ['booking_status']
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('booking:posts')

class Delete(DeleteView):
    model = Booking
    template_name = 'booking/confirm-delete.html'

booking/templates/booking/add.html
{% extends 'booking/base.html' %}
{% load widget_tweaks %}
{% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:posts' %}">Manage</a>
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:add' %}">Add New</a>
</nav>
<div class="containter pt-5">
    <form method="post" novalidate enctype='multipart/form-data'>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <div class="form-group">
        <button type="submit" class="btn btn-success">Add
        </button>
        <a href="{% url 'booking:posts' %}" class="btn btn-danger">Cancel</a>
    </div>
    </form>
</div>
{% endblock %}

booking/templates/booking/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Booking</title>
    <meta name="viewport" content="width-device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    {% include 'booking/navbar.html' %}
    {%  block content %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {% include 'booking/footer.html' %}
</body>
</html>

booking/templates/booking/confirm-delete.html
{% extends 'bookinge/base.html' %}
{% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:posts' %}">Manage</a>
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:add' %}">Add New</a>
</nav>
<div class="containter pt-5">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure want to delete "{{ object }}"</p>
        <input type="submit" value="Confirm">
    </form>
</div>
{% endblock %}

booking/templates/booking/footer.html
<!-- Footer -->
<footer class="page-footer font-small teal pt-4">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">Booking
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

booking/templates/booking/index.html
{% extends 'booking/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for booking in index %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{{ booking.coworking_space.image.url }}" alt="Card Image Cap" style = 'object-fit:cover; width: 150px; height: 100px;'>
                        <div class="card-body">
                            <h4 class=""><a href="{{ booking.get_absolute_url }}">{{ booking.id }}</a></h4>
                                <p class="card-text"></p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

booking/templates/booking/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand d-flex align-items-center" href="/">Booking</a>
      {% if user.is_superuser %}
      <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:posts' %}">Manage</a>
      <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:add' %}">Add New</a>
      {%endif%}
  
</nav>

booking/templates/booking/posts.html
{% extends 'booking/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for post in posts_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{{ post.coworking_space.image.url }}" alt="Card Image Cap" style = 'object-fit:cover; width: 150px; height: 100px;'>
                        <div class="card-body">
                            <h4 class="lead"><a class="text-dark" href="{{ post.get_absolute_url }}"> {{ post.id }}</a></h4>
                                <p class="card-text"></p>
                            <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group"></div>
                                <a href="{% url 'booking:edit' post.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Edit Booking</a>
                                <a href="{% url 'booking:cancel' post.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Cancel Booking</a>
                                <a href="{% url 'booking:delete' post.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

booking/templates/booking/single.html
{% extends 'booking/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 pt-5">
                <img class="card-img-top" src="{{ post.coworking_space.image.url }}" alt="Card Image Cap" style="height:300px;" />
                <h2 class=""pt-5>{{ post.id }}</h2>
                <p>Ticket Amount {{ post.ticket_amount }}</p>
                <p>Booking Status {{ post.booking_status }}</p>
                <p>Payment Status {{ post.payment_status }}</p>
            </div>
            <a href="{% url 'booking:edit' pk=post.id%}" class="btn btn-warning">Edit</a>
            <a href="{% url 'booking:cancel' pk=post.id%}" class="btn btn-danger">Cancel</a>
    </div>
</div>
{% endblock %}

booking/templates/booking/update.html
{% extends 'booking/base.html' %}
{% load widget_tweaks %}
{% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:posts' %}">Manage</a>
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:add' %}">Add New</a>
</nav>
<div class="containter pt-5">
    <form method="post" novalidate enctype='multipart/form-data'>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <div class="form-group">
        <button type="submit" class="btn btn-success">Add
        </button>
        <a href="{% url 'booking:posts' %}" class="btn btn-danger">Cancel</a>
    </div>
    </form>
</div>
{% endblock %}

booking/templates/booking/update_cancel.html
{% extends 'booking/base.html' %}
{% load widget_tweaks %}
{% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:posts' %}">Manage</a>
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:add' %}">Add New</a>
</nav>
<div class="containter pt-5">
    <form method="post" novalidate enctype='multipart/form-data'>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <div class="form-group">
        <button type="submit" class="btn btn-success">Submit
        </button>
        <a href="{% url 'booking:posts' %}" class="btn btn-danger">Cancel</a>
    </div>
    </form>
</div>
{% endblock %}

booking/templates/booking/update_verify.html
{% extends 'booking/base.html' %}
{% load widget_tweaks %}
{% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:posts' %}">Manage</a>
    <a class="navbar-brand d-flex align-items-center" href="{% url 'booking:add' %}">Add New</a>
</nav>
<div class="containter pt-5">
    <form method="post" novalidate enctype='multipart/form-data'>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <div class="form-group">
        <button type="submit" class="btn btn-success">Submit
        </button>
        <a href="{% url 'booking:posts' %}" class="btn btn-danger">Cancel</a>
    </div>
    </form>
</div>
{% endblock %}