coworkingSpace/urls.py
from django.urls import path
from . import views

app_name = 'coworkingSpace'

urlpatterns = [
    path('coworkingSpace/', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name="add"),
    path('posts/', views.PostsView.as_view(), name="posts"),
    path('coworkingSpace/<slug:slug>/', views.SingleView.as_view(), name='single'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
    path('add_favorit/<int:id>/', views.add_favorit, name='add_favorit'),
    path('delete_favorit/<int:id>/', views.delete_favorit, name='delete_favorit'),
    path("search_result/", views.SearchResultsView.as_view(), name="search_results"),
    path("search/", views.SearchView.as_view(), name="search"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('coworkingSpace.urls', namespace='coworkingSpace')),
    path('', include('booking.urls', namespace='booking')),
    path('accounts/', include('accounts.urls'))
]

main/urls.py
from django.urls import path

from main.views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
]

coworkingSpace/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class CoworkingSpace(models.Model):
    nama = models.CharField(max_length=200)
    alamat = models.CharField(max_length=200)
    harga = models.CharField(max_length=100)
    kapasitas = models.CharField(max_length=5, default='1')
    detail = models.TextField(null=True)
    slug = models.SlugField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='static/spaces/')
    favorit = models.ManyToManyField(User, related_name='favorit', blank=True)

    def get_absolute_url(self):
        return reverse('coworkingSpace:single', args = [self.slug])

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.nama

coworkingSpace/forms.py
from django import forms
from .models import CoworkingSpace

class PostForm(forms.ModelForm):
    class Meta:
        model=CoworkingSpace
        fields="__all__"

coworkingSpace/views.py
from .models import CoworkingSpace
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView, TemplateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect

class IndexView(ListView):
    model = CoworkingSpace
    template_name = 'coworkingSpace/index.html'
    context_object_name = 'index'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for x in context['index']:
            if x.favorit.filter(id=self.request.user.id).exists():
                x.is_favorit = True
        return context

class SingleView(DetailView):
    model = CoworkingSpace
    template_name = 'coworkingSpace/single.html'
    context_object_name = 'post'

class PostsView(ListView):
    model = CoworkingSpace
    template_name = 'coworkingSpace/posts.html'
    context_object_name = 'posts_list'

class AddView(CreateView):
    model = CoworkingSpace
    template_name = 'coworkingSpace/add.html'
    fields = '__all__'
    success_url = reverse_lazy('coworkingSpace:posts')

class EditView(UpdateView):
    model = CoworkingSpace
    template_name = 'coworkingSpace/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('coworkingSpace:posts')

class Delete(DeleteView):
    model = CoworkingSpace
    template_name = 'coworkingSpace/confirm-delete.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('coworkingSpace:posts')

def add_favorit(request, id):
    try:
        coworkingSpace = CoworkingSpace.objects.get(id=id)
        coworkingSpace.favorit.add(request.user)
        return redirect('/accounts/ruang_favorit/')
    except:
        messages.error(request, 'Error')

    return redirect('/coworkingSpace/')

def delete_favorit(request, id):
    try:
        coworkingSpace = CoworkingSpace.objects.get(id=id)
        coworkingSpace.favorit.remove(request.user)
        return redirect('/accounts/ruang_favorit/')
    except:
        messages.error(request, 'Error')
    
    return redirect('/coworkingSpace/')

class SearchView(TemplateView):
    model = CoworkingSpace
    template_name = 'coworkingSpace/search.html'

class SearchResultsView(ListView):
    model = CoworkingSpace
    template_name = 'coworkingSpace/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = CoworkingSpace.objects.filter(
            Q(nama__icontains=query)
        )

        for x in object_list:
            if x.favorit.filter(id=self.request.user.id).exists():
                x.is_favorit = True

        return object_list

coworkingSpace/templates/coworkingSpace/add.html
{% extends 'coworkingSpace/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <style>
        * {
            box-sizing: border-box;
        }
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #F8F7F3;
        }

        input[type=text], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;
        }

        label {
            padding: 12px 12px 12px 0;
            display: inline-block;
        }

        input[type=submit] {
            background-color: #04AA6D;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            float: right;
        }

        input[type=submit]:hover {
            background-color: #45a049;
        }

        .container {
            border-radius: 5px;
            background-color: #F8F7F3;
            padding: 20px;
        }

        /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
        @media screen and (max-width: 600px) {
            .col-25, .col-75, input[type=submit] {
                width: 100%;
                margin-top: 0;
            }
        }
    </style>
    <div class="container">
        <form method="post" novalidate enctype='multipart/form-data'>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                    {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="form-group">
                <button type="submit" class="btn btn-success">Add
                </button>
                <a href="{% url 'coworkingSpace:posts' %}" class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

coworkingSpace/templates/coworkingSpace/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coworking Space</title>
    <meta name="viewport" content="width-device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <link rel="shortcut icon" type="image/png" href="https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Search_ballonicon2.svg/768px-Search_ballonicon2.svg.png"/>
</head>
<body>
    {% include 'coworkingSpace/navbar.html' %}
    {%  block content %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {% include 'coworkingSpace/footer.html' %}
</body>
</html>

coworkingSpace/templates/coworkingSpace/confirm-delete.html
{% extends 'coworkingSpace/base.html' %}
{% block content %}
    <style>
        * {
            box-sizing: border-box;
        }
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #F8F7F3;
        }

        input[type=text], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;
        }

        label {
            padding: 12px 12px 12px 0;
            display: inline-block;
        }

        input[type=submit] {
            background-color: white;
            border: 2px solid #f44336;
            padding: 12px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            margin: 2px 2px;
            border-radius: 4px;
            transition-duration: 0.4s;
            cursor: pointer;
            float: right;
            color: black;
        }

        input[type=submit]:hover {
            background-color: #f44336;
            color: white;
        }

        .container {
            border-radius: 5px;
            background-color: #F8F7F3;
            padding: 20px;
        }

        /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
        @media screen and (max-width: 600px) {
            .col-25, .col-75, input[type=submit] {
                width: 100%;
                margin-top: 0;
            }
        }
    </style>

    <div class="container">
        <form method="post">
            {% csrf_token %}
            <h1>Are you sure want to delete "{{ object }}"</h1>
            <input type="submit" value="Confirm">
        </form>
    </div>
{% endblock %}

coworkingSpace/templates/coworkingSpace/edit.html
{% extends 'coworkingSpace/base.html' %}
{% load widget_tweaks %}
{% block content %}
        <style>
        * {
            box-sizing: border-box;
        }
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #F8F7F3;
        }

        input[type=text], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;
        }

        label {
            padding: 12px 12px 12px 0;
            display: inline-block;
        }

        input[type=submit] {
            background-color: #04AA6D;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            float: right;
        }

        input[type=submit]:hover {
            background-color: #45a049;
        }

        .container {
            border-radius: 5px;
            background-color: #F8F7F3;
            padding: 20px;
        }

        /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
        @media screen and (max-width: 600px) {
            .col-25, .col-75, input[type=submit] {
                width: 100%;
                margin-top: 0;
            }
        }
    </style>
<div class="container">
    <form method="post" novalidate enctype='multipart/form-data'>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <div class="form-group">
        <button type="submit" class="btn btn-success">Add
        </button>
        <a href="{% url 'coworkingSpace:posts' %}" class="btn btn-danger">Cancel</a>
    </div>
    </form>
</div>
{% endblock %}

coworkingSpace/templates/coworkingSpace/footer.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #F8F7F3;
            color: #666;
            text-align: center;

        }
        p {
            float: start;
        }

        p a {
            display: block;
            color: #666;
            text-align: center;
            text-decoration: none;
        }
    </style>
</head>
<body>
<div class="footer">
    <p><a href="/coworkingSpace">KerjaKuy</a></p>
</div>

</body>
</html>

coworkingSpace/templates/coworkingSpace/index.html
{% extends 'coworkingSpace/base.html' %}

{% block content %}
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #F8F7F3;
        }

        .flip-card {
            background-color: transparent;
            width: 350px;
            height: 230px;
            perspective: 1000px;
        }

        .flip-card-inner {
            position: relative;
            width: 100%;
            height: 100%;
            text-align: center;
            transition: transform 0.6s;
            transform-style: preserve-3d;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,2);
        }

        .flip-card:hover .flip-card-inner {
            transform: rotateY(180deg);
        }

        .flip-card-front, .flip-card-back {
            position: absolute;
            width: 100%;
            height: 100%;
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
        }

        .flip-card-front {
            background-color: white;
            color: black;
        }

        .flip-card-back {
            background-color: white;
            color: black;
            transform: rotateY(180deg);
        }
    </style>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for coworkingSpace in index %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <div class="flip-card">
                                <div class="flip-card-inner">
                                    <div class="flip-card-front">
                                        <img src="{{ coworkingSpace.image.url }}" alt="Card Image Cap" style="max-width:100%; height:auto">
                                    </div>
                                    <div class="flip-card-back">
                                        <h4><a href="{{ coworkingSpace.get_absolute_url }}">{{ coworkingSpace.nama }}</a></h4>
                                        <p>Alamat : {{ coworkingSpace.alamat}}</p>
                                        <p>Rp. {{ coworkingSpace.harga}} ,-</p>
                                    </div>
                                </div>
                            </div>
                            {% if not coworkingSpace.is_favorit %}
                                <a href="{% url 'coworkingSpace:add_favorit' coworkingSpace.id %}"><i class="fa-regular fa-heart"></i></a>
                            {% else %}
                                <a href="{% url 'coworkingSpace:delete_favorit' coworkingSpace.id %}"><i class="fa fa-heart"></i></a>
                            {% endif %}
                        </div>
                    <br>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

coworkingSpace/templates/coworkingSpace/navbar.html
<!DOCTYPE html>
<html>
<head>
    <style>
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #F8F7F3;
        }

        li {
            float: left;
        }

        li a {
            display: block;
            color: #666;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
    </style>
</head>
<body>

<ul>
    <li><a class="navbar-brand d-flex align-items-center" href="/coworkingSpace">KerjaKuy</a></li>
    {% if user.is_superuser %}
        <li><a class="navbar-brand d-flex align-items-center" href="{% url 'coworkingSpace:posts' %}">Manage</a></li>
        <li><a class="navbar-brand d-flex align-items-center" href="{% url 'coworkingSpace:add' %}">Add New</a></li>
    {%endif%}
</ul>

</body>
</html>

coworkingSpace/templates/coworkingSpace/posts.html
{% extends 'coworkingSpace/base.html' %}

{% block content %}
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #F8F7F3;
        }
        .flip-card {
            background-color: transparent;
            width: 350px;
            height: 230px;
            perspective: 1000px;
        }

        .flip-card-inner {
            position: relative;
            width: 100%;
            height: 100%;
            text-align: center;
            transition: transform 0.6s;
            transform-style: preserve-3d;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,2);
        }

        .flip-card:hover .flip-card-inner {
            transform: rotateY(180deg);
        }

        .flip-card-front, .flip-card-back {
            position: absolute;
            width: 100%;
            height: 100%;
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
        }

        .flip-card-front {
            background-color: white;
            color: black;
        }

        .flip-card-back {
            background-color: white;
            color: black;
            transform: rotateY(180deg);
        }
        .button {
            background-color: #4CAF50; /* Green */
            border: none;
            color: white;
            padding: 1px 1px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 5px;
            margin: 2px 2px;
            border-radius: 4px;
            transition-duration: 0.4s;
            cursor: pointer;
        }
        .button1 {
            background-color: white;
            color: black;
            border: 2px solid #4CAF50;
        }

        .button1:hover {
            background-color: #4CAF50;
            color: white;
        }

        .button3 {
            background-color: white;
            color: black;
            border: 2px solid #f44336;
        }

        .button3:hover {
            background-color: #f44336;
            color: white;
        }
    </style>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for post in posts_list %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <div class="card mb-4 box-shadow">
                                <div class="flip-card">
                                    <div class="flip-card-inner">
                                        <div class="flip-card-front">
                                            <img src="{{ post.image.url }}" alt="Card Image Cap" style="max-width:100%; height:auto">
                                        </div>
                                        <div class="flip-card-back">
                                            <h4><a href="{{ post.get_absolute_url }}">{{ post.nama }}</a></h4>
                                            <button class="button button1"><a href="{% url 'coworkingSpace:edit' post.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Edit</a></button>
                                            <button class="button button3"><a href="{% url 'coworkingSpace:delete' post.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Delete</a></button   >
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <br>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

coworkingSpace/templates/coworkingSpace/search.html
{% extends 'coworkingSpace/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand d-flex align-items-center" href="{% url 'coworkingSpace:posts' %}">Manage</a>
    <a class="navbar-brand d-flex align-items-center" href="{% url 'coworkingSpace:add' %}">Add New</a>
</nav>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
          <form class="form-inline my-2 my-lg-0" action="{% url 'coworkingSpace:search_results' %}" method="get">
            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">Search</button>
          </form>
        </div>
    </div>
</div>
{% endblock %}
<h1>HomePage</h1>

coworkingSpace/templates/coworkingSpace/search_results.html
{% extends 'coworkingSpace/base.html' %}

<<<<<<< HEAD
<ul>
  {% for city in object_list %}
    <li>
      {% block content %}
      <div class="album py-5 bg-light">
          <div class="container">
              <div class="row">
                  {% for coworkingSpace in index %}
                      <div class="col-md-4">
                          <div class="card mb-4 box-shadow">
                              <img class="card-img-top" src="https://via.placeholder.com/150x100" alt="Card Image Cap">
                              <div class="card-body">
                                  <h4 class=""><a href="{{ coworkingSpace.get_absolute_url }}">{{ coworkingSpace.nama }}</a></h4>
                                      <p class="card-text"></p>
                                  <div class="d-flex justify-content-between align-items-center">
                                  </div>
                                  {% if not coworkingSpace.is_favorit %}
                                        <a href="{% url 'coworkingSpace:add_favorit' coworkingSpace.id %}"><i class="fa-regular fa-heart"></i></a>
                                    {% else %}
                                        <a href="{% url 'coworkingSpace:delete_favorit' coworkingSpace.id %}"><i class="fa fa-heart"></i></a>
                                    {% endif %}
                              </div>
                          </div>
                      </div>
                  {% endfor %}
              </div>
          </div>
      </div>
      {% endblock %}
    </li>
  {% endfor %}
</ul>
=======
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for search in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="{{ search.image.url }}" alt="Card Image Cap" style = 'object-fit:cover; width: 150px; height: 100px;'>
                    <div class="card-body">
                        <h4 class="lead"><a class="text-dark" href="{{ search.get_absolute_url }}"> {{ search.nama }}</a></h4>
                            <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group"></div>
                            <a href="{% url 'coworkingSpace:edit' search.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Edit</a>
                            <a href="{% url 'coworkingSpace:delete' search.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}
>>>>>>> acf51c47057a353cf93f0f7391672593fc9184a5

coworkingSpace/templates/coworkingSpace/single.html
{% extends 'coworkingSpace/base.html' %}

{% block content %}
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #F8F7F3;
        }
        .container {
            position: relative;
            width: 50%;
        }

        .image {
            opacity: 1;
            display: block;
            width: 100%;
            height: auto;
            transition: .5s ease;
            backface-visibility: hidden;
        }

        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%)
        }

        .container:hover .image {
            opacity: 0.3;
        }

        .container:hover .middle {
            opacity: 1;
        }

        .text {
            color: black;
            font-size: 16px;
        }
    </style>
    <div class="container">
        <div class="row">
                <img class="image" src="{{ post.image.url }}" alt="Card Image Cap" style="max-width:100%; height:auto" />
                <div class="middle">
                    <div class="text"><h2>{{ post.nama }}</h2></div>
                    <br>
                    <div class="text">Harga : Rp {{ post.harga }},-</div>
                    <div class="text">Alamat : {{ post.alamat }}</div>
                    <div class="text">{{ post.detail }}</div>
            </div>
        </div>
    </div>
{% endblock %}