booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('booking/', views.IndexView.as_view(), name='index'),
    path('booking/<int:pk>', views.SingleView.as_view(), name='single'),
    path('booking/add/', views.AddView.as_view(), name="add"),
    path('booking/posts/', views.PostsView.as_view(), name="posts"),
    path('booking/edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('booking/verify/<int:pk>/', views.VerifyView.as_view(), name='verify'),
    path('booking/cancel/<int:pk>/', views.CancelView.as_view(), name='cancel'),
    path('booking/delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('coworkingSpace.urls', namespace='coworkingSpace')),
    path('', include('booking.urls', namespace='booking')),
    path('accounts/', include('accounts.urls'))
]

main/urls.py
from django.urls import path

from main.views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

main/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'styles.css' %}">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
      <link rel="shortcut icon" type="image/png" href="https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Search_ballonicon2.svg/768px-Search_ballonicon2.svg.png"/>
      <title>{% block title %}KerjaKuy{% endblock %}</title>
   </head>
   <body>
      <div id="page-container">
      {% include 'navbar.html' %}
      <div id="content-wrap">
         <div class="container content">
            {% block content %}
            {% include 'main/includes/messages.html' %}
            {% endblock %}
         </div>
      </div>
      {% include 'footer.html' %}
      </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      <script src="{% static 'index.js' %}"></script>
   </body>
</html>

main/templates/footer.html
<footer>
    <div class="footer">&copy; <span> 2022 KerjaKuy. All rights reserved.</span></div>
</footer>

main/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
   <section id="content" class="content">
      <div class="d-flex align-items-center flex-column">
         <div class="home-text">
            <h1>
                  Book your space.<br>
                  Be productive. 
            </h1>
         </div>
      </div>
   </section>
</main>
{% endblock content %}

main/templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

main/templates/navbar.html
<header class="header-area overlay">
   <nav class="navbar navbar-expand-md navbar-dark">
     <div class="container">
        <a class="navbar-brand" href="{% url 'main:home' %}">KerjaKuy</a>
        
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#main-nav">
           <span class="menu-icon-bar"></span>
           <span class="menu-icon-bar"></span>
           <span class="menu-icon-bar"></span>
        </button>
        
        <div id="main-nav" class="collapse navbar-collapse">
           <ul class="navbar-nav ml-auto">
              <li><a class="nav-item nav-link" href="{% url 'coworkingSpace:index' %}">Coworking Space</a></li>
              {% if user.is_superuser %}
              <li><a class="nav-item nav-link" href="{% url 'coworkingSpace:posts' %}">Manage</a></li>
              <li><a class="nav-item nav-link" href="{% url 'coworkingSpace:add' %}">Add New</a></li>
              {% endif %}
              {% if user.is_authenticated %}
              <li class="dropdown">
               <a class="nav-item nav-link" href="#" data-toggle="dropdown">
                  {{ user.username }}
               </a>
               <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'update_profile' %}">Profile</a>
                  <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                  <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
               </div>
               </li>
              {% else %}
              <li><a class="nav-item nav-link" href="{% url 'login' %}">Log in</a></li>
              <li><a class="nav-item nav-link" href="{% url 'register' %}">Sign up</a></li>
              {% endif %}
           </ul>
        </div>
     </div>
  </nav>
</header>